BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS feeds(
    url STRING PRIMARY KEY,
	title STRING NOT NULL,
	description STRING NOT NULL,
	last_updated TIMESTAMP,
	tags STRING[]
);

CREATE TABLE IF NOT EXISTS tags
	(name STRING NOT NULL PRIMARY KEY,
	favorite BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS articles(
    url STRING NOT NULL PRIMARY KEY,
	title STRING NOT NULL,
	description STRING,
	pubdate TIMESTAMP,
	tags STRING[],
	read BOOL
);

CREATE TABLE IF NOT EXISTS comments(
    article STRING NOT NULL,
	feed STRING NOT NULL,
	comments STRING NOT NULL PRIMARY KEY
);
COMMIT;