BEGIN TRANSACTION;
ALTER TABLE articles DROP COLUMN IF EXISTS description;

CREATE TABLE IF NOT EXISTS archive(
    article STRING NOT NULL PRIMARY KEY,
    contents STRING NOT NULL,
);

ALTER TABLE articles ADD COLUMN IF NOT EXISTS archive STRING;

COMMIT;